### ISSUE TITLE
Mix between SMD and THT ends up in SMD only footprint

### ISSUE THREAD

**Issue by Bouni** [TousstNicolas/JLC2KiCad_lib#1]
Hi,

first of all, this is absolutely amazing! I totally love this project 😍 

I tried to get footprint, symbol and 3D file for the [USB Micro connector]() `C132563 ` which should look like this:

![image](https://user-images.githubusercontent.com/948965/147727579-7f5ed57d-99e1-46b1-968a-5528fb4033d8.png)

The Symbol is correct:

![image](https://user-images.githubusercontent.com/948965/147727613-4de19bcf-e9aa-48da-8658-22b6acc72fca.png)

But the footprint is not:

![image](https://user-images.githubusercontent.com/948965/147727678-b674b8cd-35d8-4770-8d28-573a75f6221d.png)

The 3D Package turned out great:

![image](https://user-images.githubusercontent.com/948965/147727800-07cef7f8-40cd-4f21-8d2d-3cea2162af60.png)

But there are two minor issues with the 3D package:

1. The path that is put into the footprint is an absolute path, so If I generate the part lets say in C:\temp\footprints\... , that path is put into the footprint. It breaks as soon as I move the package to another location.
2. The position of the 3D model in relation to the footprint is not correct and needs to be adjusted manually, but I have no idea if thats even automatically possible.

**Comment by TousstNicolas** [comment]
Thank you for the comment and  reporting this issue. I corrected the missing holes for SMD-THT mixed components. 

I had no problem with the 3d model path on my side as long as the package is not moved, can you specify what the problem is on your side? 

I have added a `--model_path_relative` option which allows if it is present, to give the relative 3d model path. It is then formed as: `{output_dir/footprint_dir}/packages3d/{footprint_name}`
Let me now if you think there is a better solution.

**Comment by Bouni** [comment]
Let me check this next week and I'll happily give you feedback! 
Keep up the good work 😊

**Comment by Bouni** [comment]
Sorry for the late reply, I can confirm that the `--model_path_relative` switch works as expected!
