### ISSUE TITLE
Poor symbol origin placement

### ISSUE THREAD

**Issue by Xyntexx** [TousstNicolas/JLC2KiCad_lib#34]
For some parts the symbol is very far from the origin:

C82942
![image](https://user-images.githubusercontent.com/21282105/213913277-e9c71578-2241-4d3a-a374-e5d8b096713f.png)

C6649
![image](https://user-images.githubusercontent.com/21282105/213913310-354da8bd-fdc4-4c1e-bdbc-396acc202944.png)

C698918
![image](https://user-images.githubusercontent.com/21282105/213913322-2ac21cbc-aa3e-45ab-84fa-82fa7b8363fb.png)

Any ideas what's causing this?

**Comment by TousstNicolas** [comment]
Yes it is something that happens on a lot of components. The eeschema center it automatically once placed so I didn't pushed to find the issue here. 

EasyEDA use a different coordinate system, so for every schematic, I need to scale and translate everything. 

for example with the pins : 
https://github.com/TousstNicolas/JLC2KiCad_lib/blob/bb11e2d853b4c3ae273d344b61636c0bbf725295/JLC2KiCadLib/schematic/schematic_handlers.py#L95-L96

For most components it works fine, but for others, it is completely off-centerer. 
There might be a flag or an  additional translation indications somewhere in the data, but I did not found it.

**Comment by TousstNicolas** [comment]
I think I found the missing data, I will test if this works consistently and patch it.
