### ISSUE TITLE
Symbol labels missing when importing part C150858

### ISSUE THREAD

**Issue by markusdd** [TousstNicolas/JLC2KiCad_lib#65]
Part C150858 (Skyworks RFX2411) in a QFN-20 package is not being generated properly.

The designations seem correct, but all the visual pin labels are missing:
![grafik](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/25175069/5567a631-1e65-4ba3-9b2d-bc9b6da685d8)

The EasyEDA symbol has them:
![grafik](https://github.com/TousstNicolas/JLC2KiCad_lib/assets/25175069/d2ea6c72-f612-4579-afd8-cac6965011d5)

I have updated to 1.0.30, same issue as in 1.0.18 which I used before.

**Comment by TousstNicolas** [comment]
Hi, thanks for reporting this issue.

Unless I am mistaken, KiCad does not allow hiding only one pin name, while EasyEDA allows it. In KiCad, the pin name option is defined in the symbol properties and is applied to all pins. 
This is the case for pin 21, which has a hidden pin name on EasyEDA.

For symbols I tested this on, most of them either had no pin name hidden or all of them. Therefore, if one of them is hidden, I apply it on all pins. As a first fix, you can manually edit the symbol property to set the "show pin name" option.

Another solution is instead of hiding all the pin names, to set the pin name to an empty string. It would have the same visual effect, but the pin name information is lost.

Let me know what you think.

**Comment by markusdd** [comment]
I think this probably then becomes an issue for many QFN cases because all of them have these middle GND thermal pads.

I would say it is probably not a 'fail safe default' to then hide all pins in the KiCAD output.

**Comment by markusdd** [comment]
Thanks a lot!
